# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Log', '0002_auto_20170201_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('travelFrom', models.CharField(max_length=10)),
                ('travelTo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.User')),
            ],
        ),
        migrations.CreateModel(
            name='TripList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='black.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.User')),
            ],
        ),
    ]
